### ISSUE TITLE
How To Uninstall

### ISSUE THREAD

**Issue by rmorshea** [alex-spataru/HiDPI-Fixer#1]
How can I stop this script from running on login.

**Comment by alex-spataru** [comment]
Hi, 

There are many ways that you can disable the startup script:

- You can use the "Startup Applications" program to enable or disable the script. Look for the item called "Apply HiDPI Config for `<Display Name>`".
- If you don't have access to the GUI (or for some reason its unreadable), open a terminal (or TTY) and type the following:
```
cd ~/.config/autostart/         # Go to startup applications directory
rm <DisplayName>.desktop        # In my case, the file is called eDP-1.desktop
```

Let me know if you need more help, probably I'll write the code to manage startup scripts directly from the HiDPI-Fixer application.

**Comment by rmorshea** [comment]
Thanks! I managed to read in the code to figure out where things were saved on my own.

Should probably include uninstall instructions in the README until you have that autostart manager done.

**Comment by alex-spataru** [comment]
Hi, I have added a terminal option (`--uninstall`) to remove all the files generated by HiDPI Fixer, you can check the README for more information. 

Thanks for the idea!
