### ISSUE TITLE
desktop file missing Categories=

### ISSUE THREAD

**Issue by probonopd** [alex-spataru/HiDPI-Fixer#2]
The `*.desktop` file is lacking a `Categories=` entry.

According to the [menu spec](https://standards.freedesktop.org/menu-spec/latest/apa.html),

> By including one of the Main Categories in an application's desktop entry file, the application will be ensured that it will show up in a section of the application menu dedicated to this category. If multiple Main Categories are included in a single desktop entry file, the entry may appear more than once in the menu. 

Hence, please add at least one of the following in the `Categories=` key.

Main Category | Description | Notes
-- | -- | --
AudioVideo | Application for presenting, creating, or processing multimedia (audio/video) |  
Audio | An audio application | Desktop entry must include AudioVideo as well
Video | A video application | Desktop entry must include AudioVideo as well
Development | An application for development |  
Education | Educational software |  
Game | A game |  
Graphics | Application for viewing, creating, or processing graphics |  
Network | Network application such as a web browser |  
Office | An office type application |  
Science | Scientific software |  
Settings | Settings applications | Entries may appear in a separate menu or as part of a 		"Control Center"
System | System application, "System Tools" such as say a log viewer or network monitor |  
Utility | Small utility application, "Accessories"

In addition, you could specify one or more from the longer list of [Additional Categories](https://standards.freedesktop.org/menu-spec/latest/apas02.html).

Please test the result with `desktop-file-validate` and make sure it passes.

__electron-builder offers native support for this since [v19.22.1](https://github.com/electron-userland/electron-builder/releases/tag/v19.22.1).__. Please see the `category` key at https://www.electron.build/configuration/linux-other.

Refereces:
* https://github.com/AppImage/appimage.github.io/issues/2
* https://github.com/AppImage/appimage.github.io/pull/750

**Comment by alex-spataru** [comment]
Thanks for the information! For the moment, I did not create any desktop file for the AppImage (I used the default.desktop generated by `linuxdeployqt`), I'll work on it and keep you updated.

**Comment by alex-spataru** [comment]
Sorry, I forgot to send you a message about the `*.desktop` file updates that I made. Now `desktop-file-validate` does not return any errors or warnings. If possible, can you verify my changes so that I can close this issue?

**Comment by probonopd** [comment]
Please upload a release containing the changes to GitHub Releases, then let me know, so that I can re-run the automated test. Thanks.

**Comment by alex-spataru** [comment]
Sorry for the late reply, I did not have time to work on this project due to college. I have uploaded a new release with various improvements, please let me know if the automated test passed.

**Comment by probonopd** [comment]
Thanks, this is no longer an issue.
