### ISSUE TITLE
Uninstaller does not reset GNOME scaling-factor

### ISSUE THREAD

**Issue by fantostisch** [alex-spataru/HiDPI-Fixer#6]
After using HiDPI Fixer and then the uninstaller, the scaling-factor is not reset which results in some programs still being scaled (like Intellij Idea). The uninstaller should reset the scaling-factor:
`gsettings reset org.gnome.desktop.interface scaling-factor`.

**Comment by alex-spataru** [comment]
Sorry for the late reply. The issue should be fixed now. Could anyone please test the latest release? I don't have access to a computer/vbox with a Linux distro right now...
